/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>



#define RCC_BASE 		0x40021000
#define RCC_CR   		(*(volatile uint32_t*)(RCC_BASE + 0x00))
#define RCC_CR_HSEON	16
#define RCC_CR_HSERDY	17

#define RCC_CFGR		RCC_BASE + 0x04

int main(void)
{
	// HSE Enable
    RCC_CR |= (1 << RCC_CR_HSEON);
    while(!(RCC_CR & (1 << RCC_CR_HSERDY)));


    while (1)
    {

    }
}
